language: python
jobs:  
  include:
  - name: "Linux"
    os: linux
    python:
      - "3.4"
      - "3.8"
      - "nightly"
      - "pypy3"
  - name: "MacOS"
    language: shell
    os: osx
    osx_image: xcode11.2
  - name: "Windows"
    language: shell
    os: windows
    before_install:
      - choco install python --version 3.8.0
      - python -m pip install --upgrade pip
    env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  pip3 install --upgrade pip
  pip3 install matplotlib
  pip3 install .
script: python3 tinybench/tests/test.py || python tinybench/tests/test.py
